<img src="../Img/banner-fa-49-2.jpg">

29 марта 2021 года, ВМ/305-1(кк)<br>

# Семинар. Контрольная работа с решением

Студенты: Поток У18-7у<br>
Преподаватель: Смирнов Михаил Викторович, доцент Департамента Анализа данных и машинного обучения Финансового университета при Правительстве Российской Федерации

In [2]:
import numpy as np

### Задание 1
Имеется строка "Волшебной красоты закат озарил Красноярск". Напишите код, который меняет местами второе и третье слова.

In [2]:
# 1.

s="Волшебной красоты закат озарил Красноярск"
# Ваш код здесь
s=s.split()
s[1],s[2]=s[2],s[1]
s=" ".join(s)
print(s)

Волшебной закат красоты озарил Красноярск


### Задание 2 
Имеется фрагмент html-кода.
```
<script type="text" charset="UTF-8"></script><script id="documentation_options"></script>
```
Напишите код, возвращающий значение идентификатора *id*. Ожидается результат `documentation_options`.

In [3]:
# 2.

h='<script type="text" charset="UTF-8"></script><script id="documentation_options"></script>'
# Ваш код здесь
start=h.find("doc")
end=h.find('">',start)
print(h[start:end])

documentation_options


### Задание 3
Напишите код, который показывает, сколько раз в html-коде встречается подстрока "</".

In [4]:
# 3.

h='<script type="text" charset="UTF-8"></script><script id="documentation_options"></script>'
# Ваш код здесь
n=h.count("</")
print(n)

2


### Задание 4
Имеется вложенная структура данных, содержащая список ингредиентов греческой кухни.
```
{'cuisine': 'greek',
 'id': 10259,
 'ingredients': ['romaine lettuce',
                 'black olives',
                 'grape tomatoes',
                 'garlic',
                 'pepper',
                 'purple onion',
                 'seasoning',
                 'garbanzo beans',
                 'feta cheese crumbles']}
```
Напишите код, который возвращает число ингредиентов.

In [23]:
# 4.

food={'cuisine': 'greek',
'id': 10259,
'ingredients': ['romaine lettuce',
              'black olives',
              'grape tomatoes',
              'garlic',
              'pepper',
              'purple onion',
              'seasoning',
              'garbanzo beans',
              'feta cheese crumbles']}

# Ваш код здесь
n=len(food['ingredients'])
print(n)

9


### Задание 5
Напишите код, который распечатывает список ингредиентов кухни в алфавитном порядке.

In [24]:
# 5.

food={'cuisine': 'greek',
'id': 10259,
'ingredients': ['romaine lettuce',
              'black olives',
              'grape tomatoes',
              'garlic',
              'pepper',
              'purple onion',
              'seasoning',
              'garbanzo beans',
              'feta cheese crumbles']}

# Ваш код здесь
ingr=food['ingredients']
ingr.sort()
print(ingr)

['black olives', 'feta cheese crumbles', 'garbanzo beans', 'garlic', 'grape tomatoes', 'pepper', 'purple onion', 'romaine lettuce', 'seasoning']


### Задание 6
В списке ингредиентов тайской кухни допущена ошибка: один ингредиент указан дважды. 
```
food={'id': 13121,
      'cuisine': 'thai',
      'ingredients': ['chopped cilantro fresh', 'hoisin sauce', 
                      'creamy peanut butter', 'chopped fresh mint',
                      'thai basil', 'rice','rice','medium shrimp']}
```
Напишите код, который исключает повторяющееся значение. Результат может быть представлен в виде списка или множества ингредиентов без повторов.

In [25]:
# 6. 

food={'id': 13121,
   'cuisine': 'thai',
   'ingredients': ['chopped cilantro fresh', 'hoisin sauce', 
                   'creamy peanut butter', 'chopped fresh mint',
                   'thai basil', 'rice', 'rice', 'medium shrimp']}

# Ваш код здесь
set1=set(food['ingredients'])
print(set1)

{'rice', 'chopped fresh mint', 'medium shrimp', 'thai basil', 'hoisin sauce', 'chopped cilantro fresh', 'creamy peanut butter'}


### Задание 7
Имеется массив `arr = np.array([1, 2, 3, 4])`. Распечатайте  количество измерений данного массива.

In [3]:
# 7.

arr = np.array([1, 2, 3, 4])

# Ваш код здесь
print(arr.ndim)

1


### Задание 8
Создать NumPy массив 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [26]:
# 8. Вариант 1. С помощью среза

# Ваш код здесь
m=np.arange(1,111).reshape(11,10)
m[:,:7]

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [27]:
# 8. Вариант 2. С помощью распространения

# Ваш код здесь
ma1=np.arange(0,110,10).reshape(11,1)
ma2=np.arange(1,8).reshape(1,7)
ma+ma2

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

### Задание 9
Написать код, в результате выполнения которого матрица размера $m$ на $n$ заполняется текстурой размера 2 на 2:

```
0 1
2 3

```

Пример для $m = 4$ и $n = 5$:

```
0 1 0 1 0
2 3 2 3 2
0 1 0 1 0
2 3 2 3 2
```

In [10]:
# 9.

# Ваш код здесь
m,n = 4,5
A = np.array([0,1]*(n//2+1))[:n]
B = np.array([2,3]*(n//2+1))[:n]
Z = np.stack((A,B)*(m//2+1),axis=0)[:m]
print(Z)

[[0 1 0 1 0]
 [2 3 2 3 2]
 [0 1 0 1 0]
 [2 3 2 3 2]]


### Задание 10
Вычесть одномерный массив *B* из двумерного массива *A*, так, чтобы каждый элемент одномерного массива вычитался из всех элементов соответствующих строк массива *A*. Применить технику распространения.

_Пример:_

```
A = np.array([[3,3,3],[4,4,4],[5,5,5]])
B = np.array([1,2,3])
```

Ожидается резульат:

```
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [45]:
# 10.

# Ваш код здесь
A = np.array([[3,3,3],[4,4,4],[5,5,5]])
B = np.array([1,2,3])
B = B.reshape(3,1)
C = A-B
print(C)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


### Задание 11
Дан массив углов
```
alfas = np.array(([0.52, 0.79, 1.04, 1.57, 2.09, 2.36, 2.61]))
```
Создать массив из трех строк, состоящих из значений синусов, косинусов и тангенсов углов.

In [46]:
# 11.

alfas = np.array(([0.52, 0.79, 1.04, 1.57, 2.09, 2.36, 2.61]))

# Ваш код здесь
sin = np.sin(alfas)
cos = np.cos(alfas)
tan = np.tan(alfas)
result = np.stack((sin, cos, tan), axis=0)
print(result)

array([[ 4.96880138e-01,  7.10353272e-01,  8.62404227e-01,
         9.99999683e-01,  8.68214583e-01,  7.04410766e-01,
         5.06906852e-01],
       [ 8.67819180e-01,  7.03845316e-01,  5.06220257e-01,
         7.96326711e-04, -4.96188913e-01, -7.09792556e-01,
        -8.62000837e-01],
       [ 5.72561830e-01,  1.00924629e+00,  1.70361461e+00,
         1.25576559e+03, -1.74976619e+00, -9.92417798e-01,
        -5.88058422e-01]])

### Задание 12
Имеется массив `A = np.array([2, 6, 1, 9, 10, 3, 27])`. Получить элементы в диапазоне от 5 до 10.

In [5]:
# 12.

A = np.array([2, 6, 1, 9, 10, 3, 27])

# Ваш код здесь
A[(A>=5) & (A<=10)]

array([ 6,  9, 10])

### Задание 13
Поменять местами столбец 1 и 2 в массиве np.arange(9).reshape(3,3)

In [27]:
# 13

A = np.arange(9).reshape(3,3)

# Ваш код здесь
A = np.concatenate((A[:,0],A[:,2],A[:,1])).reshape(3,3).T
print(A)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


### Задание 14
Инвертировать порядок элементов в двумерном массиве `np.arange(9).reshape(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [43]:
# 14.

A = np.arange(9).reshape(3,3)

# Ваш код здесь
print(A, end='\n\n')
B=A[::-1,::-1]
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[8 7 6]
 [5 4 3]
 [2 1 0]]


### Задание 15
Cоздать массив из 20 случайных целых чисел от 0 до 100. Обрезать значения массива (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [15]:
# 15.

# Ваш код здесь
A = np.random.randint(0,101,size=(20))
print(A)
A[A<30]=30
A[A>70]=70
print(A)

[ 4 92 20 74 63 72 36 20 22 22 65 19 54 93 64 37 88 67 44 82]
[30 70 30 70 63 70 36 30 30 30 65 30 54 70 64 37 70 67 44 70]
