### Разбор заданий контрольной работы

In [5]:
import numpy as np

Задание 1

In [1]:
# 1.

s="Волшебный красоты закат озарил Красноярск"
# Ваш код здесь

list1 = ["Волшебный", "красоты", "закат", "озарил", "Красноярск"]
list1[1:3] = ["закат", "красоты"]

p = ''
for word in list1:
    word=word.strip()+' '
    p+=word
p[:-1]

'Волшебный закат красоты озарил Красноярск'

In [4]:
# 2.
h = "script type="text" charset="UTF-8"></script><script id="documentation_options"></script"

SyntaxError: invalid syntax (<ipython-input-4-3f885af40cff>, line 2)

In [14]:
# 11.

alfas = np.array(([0.52, 0.79, 1.04, 1.57, 2.09, 2.36, 2.61]))

# Ваш код здесь

alfas = np.array([[np.sin(alfas)], [np.cos(alfas)], [np.tan(alfas)]])
print(alfas)

[[[ 4.96880138e-01  7.10353272e-01  8.62404227e-01  9.99999683e-01
    8.68214583e-01  7.04410766e-01  5.06906852e-01]]

 [[ 8.67819180e-01  7.03845316e-01  5.06220257e-01  7.96326711e-04
   -4.96188913e-01 -7.09792556e-01 -8.62000837e-01]]

 [[ 5.72561830e-01  1.00924629e+00  1.70361461e+00  1.25576559e+03
   -1.74976619e+00 -9.92417798e-01 -5.88058422e-01]]]


In [ ]:
# 12.

A = np.array([2, 6, 1, 9, 10, 3, 27])
# Ваш код здесь

A = np.array([2, 6, 1, 9, 10, 3, 27])
# Ваш код здесь
arr = np.array([2, 6, 1, 9, 10, 3, 27])
A = [False, True, False, True, False, False, False]
newarr = arr[A]
print(newarr)

In [16]:
np.sin(1.57)

0.9999996829318346

In [ ]:
# 12.

arr = np.array([2, 6, 1, 9, 10, 3, 27])

filter_arr = []


for element in arr:
  
    if element >= 5:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
      
                 
newarr = arr[filter_arr]

print(newarr)

filter_newarr = []

for element in newarr:
    if element <= 10:
        #filter_newarrarr.append(True)

    else:
        #filter_newarrarr.append(False)


snewarr = arr[filter_newarr]

print(filter_newarr)
print(snewarr) 

In [17]:
A = np.array ([2,6,1,9,10,3,27])
import numpy as np
arr=np.array([2,6,1,9,10,3,27])
A=[False,True,False,True,False,False,False]
newarr=arr[A]
print(newarr)

[6 9]


In [18]:
A = np.array ([2,6,1,9,10,3,27])
((A>=6) & (A<=10))

array([False,  True, False,  True,  True, False, False])

In [20]:
# 13

N = np.arange(9).reshape(3,3)
import numpy as np
arr = N
N = np.arange(9).reshape(3,3)
N = arr.reshape(1,3,-1)
print(np.sort(N))
print(N)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
