<img src="../Img/banner-fa-49-2.jpg">

29 марта 2021 года, ВМ/305-1(кк)<br>

# Семинар. Контрольная работа

Студенты: Поток У18-7у<br>
Преподаватель: Смирнов Михаил Викторович, доцент Департамента Анализа данных и машинного обучения Финансового университета при Правительстве Российской Федерации

In [ ]:
import numpy as np

### Задание 1
Имеется строка "Волшебной красоты закат озарил Красноярск". Напишите код, который меняет местами второе и третье слова.

In [ ]:
# 1.

s="Волшебной красоты закат озарил Красноярск"
# Ваш код здесь


### Задание 2 
Имеется фрагмент html-кода.
```
<script type="text" charset="UTF-8"></script><script id="documentation_options"></script>
```
Напишите код, возвращающий значение идентификатора *id*. Ожидается результат `documentation_options`.

In [ ]:
# 2.

h='<script type="text" charset="UTF-8"></script><script id="documentation_options"></script>'
# Ваш код здесь


### Задание 3
Напишите код, который показывает, сколько раз в html-коде встречается подстрока "</".

In [ ]:
# 3.

h='<script type="text" charset="UTF-8"></script><script id="documentation_options"></script>'
# Ваш код здесь


### Задание 4
Имеется вложенная структура данных, содержащая список ингредиентов греческой кухни.
```
{'cuisine': 'greek',
 'id': 10259,
 'ingredients': ['romaine lettuce',
                 'black olives',
                 'grape tomatoes',
                 'garlic',
                 'pepper',
                 'purple onion',
                 'seasoning',
                 'garbanzo beans',
                 'feta cheese crumbles']}
```
Напишите код, который возвращает число ингредиентов.

In [ ]:
# 4.

food={'cuisine': 'greek',
'id': 10259,
'ingredients': ['romaine lettuce',
              'black olives',
              'grape tomatoes',
              'garlic',
              'pepper',
              'purple onion',
              'seasoning',
              'garbanzo beans',
              'feta cheese crumbles']}
# Ваш код здесь


### Задание 5
Напишите код, который распечатывает список ингредиентов кухни в алфавитном порядке.

In [ ]:
# 5.

food={'cuisine': 'greek',
'id': 10259,
'ingredients': ['romaine lettuce',
              'black olives',
              'grape tomatoes',
              'garlic',
              'pepper',
              'purple onion',
              'seasoning',
              'garbanzo beans',
              'feta cheese crumbles']}
# Ваш код здесь


### Задание 6
В списке ингредиентов тайской кухни допущена ошибка: рис указан дважды. 
```
food={'id': 13121,
      'cuisine': 'thai',
      'ingredients': ['chopped cilantro fresh', 'hoisin sauce', 
                      'creamy peanut butter', 'chopped fresh mint',
                      'thai basil', 'rice','rice','medium shrimp']}
```
Напишите код, который исключает повторяющееся значение. Результат может быть представлен в виде списка или множества.

In [ ]:
# 6. 

food={'id': 13121,
   'cuisine': 'thai',
   'ingredients': ['chopped cilantro fresh', 'hoisin sauce', 
                   'creamy peanut butter', 'chopped fresh mint',
                   'thai basil', 'rice', 'rice', 'medium shrimp']}
# Ваш код здесь


### Задание 7
Имеется массив `arr = np.array([1, 2, 3, 4])` Распечатайте  количество измерений данного массива.

In [ ]:
# 7.

arr = np.array([1, 2, 3, 4])
# Ваш код здесь


### Задание 8
Создать NumPy массив 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
# 8. Вариант 1. С помощью среза

# Ваш код здесь


In [ ]:
# 8. Вариант 2. С помощью распространения

# Ваш код здесь


### Задание 9
Написать код, в результате выполнения которого матрица размера $m$ на $n$, заполняется текстурой размера 2 на 2:

```
0 1
2 3

```

Пример для m = 4 и n = 5:

```
0 1 0 1 0
2 3 2 3 2
0 1 0 1 0
2 3 2 3 2
```

In [ ]:
# 9.

# Ваш код здесь


### Задание 10
Вычесть одномерный массив *B* из двумерного массива *A*, так, чтобы каждый элемент одномерного массива вычитался из всех элементов соответствующих строк массива *A*. Применить технику распространения.

_Пример:_

```
A = np.array([[3,3,3],[4,4,4],[5,5,5]])
B = np.array([1,2,3])
```

Ожидается резульат:

```
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [ ]:
# 10.

# Ваш код здесь


### Задание 11
Дан массив углов
```
alfas = np.array(([0.52, 0.79, 1.04, 1.57, 2.09, 2.36, 2.61]))
```
Создать массив из трех строк, состоящих из значений синусов, косинусов и тангенсов углов.

In [ ]:
# 11.

alfas = np.array(([0.52, 0.79, 1.04, 1.57, 2.09, 2.36, 2.61]))

# Ваш код здесь


### Задание 12
Имеется массив `A = np.array([2, 6, 1, 9, 10, 3, 27])`. Получить элементы в диапазоне от 5 до 10.

In [ ]:
# 12.

A = np.array([2, 6, 1, 9, 10, 3, 27])
# Ваш код здесь


### Задание 13
Поменять местами столбец 1 и 2 в массиве np.arange(9).reshape(3,3)

In [ ]:
# 13

A = np.arange(9).reshape(3,3)

# Ваш код здесь


### Задание 14
Инвертировать порядок элементов в двухмерном массиве np.arange(9).reshape(3,3) .

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [ ]:
# 14.

A = np.arange(9).reshape(3,3)

# Ваш код здесь


### Задание 15
Cоздать массив из 20 случайных целых чисел от 0 до 100. Обрезать значения массива (заменить значения выходящие за диапазон на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
# 15.

# Ваш код здесь
